# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: è¥¿ç“œğŸ‰
show_title: false
subtitle:
description:
keywords:
author: è¥¿ç“œğŸ‰
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://weisiwu.github.io
root: /
permalink: :year/:month/:day/:title.html
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: web
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
## stun theme: https://github.com/liuyib/hexo-theme-stun
theme: stun
## è‡ªå®šä¹‰themeé…ç½®: https://hexo.io/docs/configuration.html
theme_config:
  enable: true
  busuanzi: 
    enable: false
  header:
    enable: true
    bg_image:
      enable: true
      url: /images/background/bk3.jpeg
  author:
    avatar:
      animation:
      url: /images/avatar/avatar_1.jpeg
    motto: æ‚Ÿå·²å¾€ä¹‹ä¸è°ï¼ŒçŸ¥æ¥è€…ä¹‹å¯è¿½
  social_setting:
    enable: true
    icon_only: true
  social: 
    github: https://github.com/weisiwu/ || fab fa-github
    çŸ¥ä¹: https://www.zhihu.com/people/wei-si-wu || fab fa-zhihu
    ç¨€åœŸæ˜é‡‘: https://juejin.cn/user/659362706096526 || origin:æ˜é‡‘
    Segmentfault: https://segmentfault.com/u/javascriptuser || origin:SF
    é‚®ç®±: mailto:24368874745@qq.com || fa fa-envelope
    google: 
    twitter: 
    youtube:
  menu:
    categories: /categories/ || fas fa-layer-group
    tags: /tags/ || fas fa-tags
  creative_commons:
    enable: true
    sidebar: 
  footer: 
    custom: 
      enable: true
      text: 'ä¸”éšç–¾é£å‰è¡Œï¼Œèº«åäº¦éœ€ç•™å¿ƒ'
    icon:
      enable: true
      name: æ ‡ç­¾test
    copyright:
      enable: true
      since: 2019
      end: 2022
      text: è¥¿ç“œğŸ‰
      author: è¥¿ç“œğŸ‰
      beian:
        icp: 
    powered: 
      enable: true
      version: 
  # Gittalk
  # See: https://github.com/gitalk/gitalk/
  gitalk:
    enable: true
    # Github username.
    owner: weisiwu
    # Github repository.
    repo: weisiwu.github.io
    # Github Application Client ID.
    client_id: 6ddd32911a0b77477a69
    # client_id: Iv1.30a181049e1aba60
    # Github Application Client Secret.
    # client_secret: 3e59b07f07c4bc06c9930bcc8476d946621f5a26
    client_secret: 46b02925c970b5101d38a5da2c122599519423c4
    # GitHub repo owner and collaborators, only these guys can initialize github issues.
    admin: weisiwu
    # Facebook-like distraction free mode.
    distraction_free_mode: true
    # Gitalk's display language depends on user's browser or system environment.
    # If you want everyone visiting your site to see a uniform language, you can set a force language value.
    # Optional values: en | zh-CN | es-ES | fr | ru | zh-TW
    language: zh-CN
  cdn:
    # See: https://github.com/gitalk/gitalk/, https://github.com/emn178/js-md5/
    # Example:
    # gitalk_js: //cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.min.js
    # gitalk_css: //cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.css
    # md5: //cdn.jsdelivr.net/npm/js-md5@latest/src/md5.min.js
    gitalk_js: https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.min.js
    gitalk_css: https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.css


# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: